### ISSUE TITLE
slideshow off seems to be wrong?

### ISSUE THREAD

**Issue by unixhaj** [MattBlissett/Apache-Gallery#1]
Hey,

I'm using your version of A::G at nathue.dk, and the slideshow function seems to be broken a bit.

For some reason $IMAGEURI contains the file name extension when trying to turn slideshow off, which results in a 403 error..

Is this a bug or something wrong in my end?

**Comment by MattBlissett** [comment]
That was a bug, which I've fixed in the latest commit.  You'll need to remove the .html files from the cache (probably `/var/cache/www`) to allow them to be regenerated.

I've also increased the size of the slideshow links, since they were a bit small to click on.
